### ISSUE TITLE
made changes

### ISSUE THREAD

**Issue by rahulkapoor90** [VaTz88/VES-API#2]
i made win sem menu back to closed one as it was getting a little cluttered and looking like a full menu.anyone who wants to see the win sem contents can click it and open other items.

**Comment by vatz88** [comment]
ok but how about we remove the win sem header and just keep the menu options. It'll be obviously assumed that the links are for current sem

**Comment by rahulkapoor90** [comment]
I want quick menu to be small in size and that's what makes it quick. not sure how your solution will help.
